<?php

namespace Carnet\CarBundle\Repository;

/**
 * VidangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VidangeRepository extends \Doctrine\ORM\EntityRepository
{
	public function getVidangesByCar($id_car)
	{
		$query = $this->createQueryBuilder('v')
			->leftJoin('v.car', 'c')
			->addSelect('c')
			->getQuery()
		;

		return $query->getResult();
	}
}
