carnet_car_home:
    path:     /{page}
    defaults:  
        _controller: CarnetCarBundle:Car:index 
        page:        1
    requirements:
        page: \d*

carnet_car_view:
    path:     /car/{id}
    defaults: 
        _controller: CarnetCarBundle:Car:view
    requirements:
        id: \d+

carnet_car_add:
    path:     /add
    defaults:
        _controller: CarnetCarBundle:Car:add

carnet_car_update:
    path:     /update/{id}
    defaults:
        _controller: CarnetCarBundle:Car:update
    requirements:
        id: \d+

carnet_car_delete:
    path:     /delete/{id}
    defaults: 
        _controller: CarnetCarBundle:Car:delete
    requirements:
        id: \d+

carnet_vidange_view:
    path:     /vidange{id}
    defaults:
        _controller: CarnetCarBundle:Vidange:view
    requirements:
        id: \d+

carnet_vidange_add:
    path:     /car/{id_car}/vidange/add
    defaults:
        _controller: CarnetCarBundle:Vidange:add
    requirements:
        id_car: \d+

carnet_vidange_delete:
    path:     /delete/vidange/{id}
    defaults: 
        _controller: CarnetCarBundle:Vidange:delete
    requirements:
        id: \d+